version: 1.0.{build}

clone_depth: 1

configuration:
    - Debug
    - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x86
    - x64

environment:
    matrix:
        - PYTHON: C:\Python27
        - PYTHON: C:\Python35
        - JULIAVERSION: "julialang/bin/winnt/x86/0.4/julia-0.4-latest-win32.exe"
        - JULIAVERSION: "julialang/bin/winnt/x64/0.4/julia-0.4-latest-win64.exe

install:
# if there's a newer build queued for the same PR, cancel this one
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
  - C:\projects\julia\bin\julia -e "Pkg.add(\"BaseTestNext\")"

build_script:
    - "%PYTHON%\\python -m pip install --user numpy"
    - cmake --version
    - mkdir build
    - pushd build
    - cmake C:\projects\SegyIO -DBUILD_MEX=OFF -DBUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=%configuration% -DPYTHON_EXECUTABLE="%PYTHON%\\python.exe"
    - cmake --build . --config %configuration%
    - ctest -C %configuration% --output-on-failure -V
